try {
  console.log("tryブロック");
} catch(error) {
  console.log("catchブロック")
} finally {
  console.log("finallyブロック");
}

try {
  console.log("tryブロック")
} finally {
  console.log("finallyブロック");
}
